name: PeticionProgramada

on:
  schedule:
    # Ejecutar cada 14 minutos y 50 segundos
    - cron: '*/14 * * * *' # Ejecuta cada 14 minutos; ajustar según sea necesario.

jobs:
  enviarPeticionGET:
    runs-on: ubuntu-latest

    steps:
      # Comprobar el repositorio
      - name: Obtener el repositorio
        uses: actions/checkout@v2

      # Enviar solicitud GET
      - name: Enviar petición GET a la URL
        run: |
          curl -X GET https://healthy-age-backend.onrender.com/usuarios
